[package]
name = "rust_experimental"
version = "0.1.0"
edition = "2021"

[dependencies]
umya-spreadsheet = "2.2.1"
reqwest = { version = "0.12.12", default-features = false, features = ["cookies", "json", "stream"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-macros = { version = "2.5.0" }
serde_json = "1.0.135"
anyhow = "1.0.95"
