name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: quay.io/rockylinux/rockylinux:8
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Pasang Rust
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup target add x86_64-unknown-linux-musl
    - run: echo '[target.x86_64-unknown-linux-musl]' > ~/.cargo/config
    - run: echo 'linker = "rust-lld"' >> ~/.cargo/config
    - name: Build
      run: cargo build --verbose
    - name: Membangun versi musl-libc
    - run: cargo build --release --target=x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
