name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup target add x86_64-unknown-linux-musl
    - run: echo '[target.x86_64-unknown-linux-musl]' > ~/.cargo/config
    - run: echo 'linker = "rust-lld"' >> ~/.cargo/config
    - name: Membangun versi musl
      run: cargo build --release --target=x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
